#!/usr/bin/env zsh

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR:$GOPATH"
echo $GOPATH

gofmt -w src

echo "install $1"

go install $1

export GOPATH="$OLDGOPATH"

echo 'finished'
